FROM centos:centos7

ENV TERM linux
ENV DEBIAN_FRONTEND noninteractive

RUN yum -y install gcc make rpm-build tar libnetfilter queue-devel libpcap-devel gcc-c++ doxygen rpmdevtools wget vim 

CMD ["/bin/bash"]
